using System.Reflection;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: AssemblyVersionAttribute("1.4.1.3823")]
[assembly: AssemblyCopyrightAttribute("Copyright © 2008 ThoughtWorks Inc.")]
[assembly: AssemblyCompanyAttribute("ThoughtWorks")]
[assembly: AssemblyProductAttribute("CruiseControl.NET")]

