using System.Reflection;
using System.Runtime.InteropServices;
using System.Windows.Markup;

[assembly: AssemblyTitle("CruiseControl.Core")]
[assembly: AssemblyDescription("")]
[assembly: AssemblyConfiguration("")]
[assembly: AssemblyCompany("Microsoft")]
[assembly: AssemblyProduct("CruiseControl.Core")]
[assembly: AssemblyCopyright("Copyright © Microsoft 2010")]
[assembly: AssemblyTrademark("")]
[assembly: AssemblyCulture("")]
[assembly: ComVisible(false)]
[assembly: Guid("4fc131f0-73aa-4661-97a2-6faa3fab134b")]
[assembly: AssemblyVersion("1.0.0.0")]
[assembly: AssemblyFileVersion("1.0.0.0")]
[assembly: XmlnsDefinition("urn:cruisecontrol:server", "CruiseControl.Core")]
[assembly: XmlnsDefinition("urn:cruisecontrol:server", "CruiseControl.Core.Structure")]
[assembly: XmlnsDefinition("urn:cruisecontrol:server:triggers", "CruiseControl.Core.Triggers")]
[assembly: XmlnsDefinition("urn:cruisecontrol:server:tasks", "CruiseControl.Core.Tasks")]
[assembly: XmlnsDefinition("urn:cruisecontrol:server:tasks:conditions", "CruiseControl.Core.Tasks.Conditions")]
[assembly: XmlnsDefinition("urn:cruisecontrol:server:tasks:failure", "CruiseControl.Core.Tasks.FailureActions")]
[assembly: XmlnsDefinition("urn:cruisecontrol:server:sourcecontrol", "CruiseControl.Core.SourceControl")]
[assembly: XmlnsDefinition("urn:cruisecontrol:server:channels", "CruiseControl.Core.Channels")]
[assembly: XmlnsPrefix("urn:cruisecontrol:server:triggers", "triggers")]
[assembly: XmlnsPrefix("urn:cruisecontrol:server:tasks", "tasks")]
[assembly: XmlnsPrefix("urn:cruisecontrol:server:tasks:conditions", "conditions")]
[assembly: XmlnsPrefix("urn:cruisecontrol:server:tasks:failure", "failure")]
[assembly: XmlnsPrefix("urn:cruisecontrol:server:sourcecontrol", "scm")]
[assembly: XmlnsPrefix("urn:cruisecontrol:server:channels", "channels")]